//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderApp_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRATOR
    {
        public string ADMINISTRATOR_ID { get; set; }
        public string ADMINISTRATOR_NAME { get; set; }
        public string ADMINISTRATOR_USERNAME { get; set; }
        public string ADMINISTRATOR_PASSWORD { get; set; }
    }
}
