//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderApp_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public string BILL_ID { get; set; }
        public Nullable<System.DateTime> BILL_DATE { get; set; }
        public Nullable<int> TOTAL_PRICE { get; set; }
    }
}
