//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderApp_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public string PRODUCT_ID { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string IMAGE_PATH { get; set; }
        public Nullable<int> PRICE { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
    }
}
