//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderApp_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RECEIPT()
        {
            this.RECEIPT_DETAIL = new HashSet<RECEIPT_DETAIL>();
        }
    
        public string RECEIPT_ID { get; set; }
        public System.DateTime RECEIPT_DATE { get; set; }
        public int RECEIPT_VALUE { get; set; }
        public string CUSTOMER { get; set; }
        public string RECEIPT_STATUS { get; set; }
    
        public virtual CUSTOMER CUSTOMER1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT_DETAIL> RECEIPT_DETAIL { get; set; }
    }
}
