//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderApp_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RECEIPT_DETAIL
    {
        public string DETAIL_ID { get; set; }
        public string RECEIPT_ID { get; set; }
        public string PRODUCT { get; set; }
        public short AMOUNT { get; set; }
    
        public virtual PRODUCT PRODUCT1 { get; set; }
        public virtual RECEIPT RECEIPT { get; set; }
    }
}
