//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodOrderApp_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USER()
        {
            this.RECEIPTs = new HashSet<RECEIPT>();
        }
    
        public string USER_USERNAME { get; set; }
        public string USER_PASSWORD { get; set; }
        public string USER_FULLNAME { get; set; }
        public string USER_ADDRESS { get; set; }
        public string USER_SEX { get; set; }
        public string USER_PHONE { get; set; }
        public string USER_EMAIL { get; set; }
        public string USER_TYPE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECEIPT> RECEIPTs { get; set; }
    }
}
